/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedApiAccessIndexRouteImport } from './routes/_authenticated/api-access/index'
import { Route as AuthenticatedApiAccessNewRouteImport } from './routes/_authenticated/api-access/new'
import { Route as AuthenticatedProvidersIndexRouteImport } from './routes/_authenticated/providers/index'
import { Route as AuthenticatedProvidersSlugRouteImport } from './routes/_authenticated/providers/$slug'
import { Route as AuthenticatedProvidersNewRouteImport } from './routes/_authenticated/providers/new'
import { Route as AuthenticatedVaultIndexRouteImport } from './routes/_authenticated/vault/index'
import { Route as AuthenticatedVaultIdRouteImport } from './routes/_authenticated/vault/$id'
import { Route as AuthenticatedVaultExportRouteImport } from './routes/_authenticated/vault/export'
import { Route as AuthenticatedVaultImportRouteImport } from './routes/_authenticated/vault/import'
import { Route as AuthenticatedVaultNewRouteImport } from './routes/_authenticated/vault/new'
import { Route as ApiPublicSetupAdminRouteImport } from './routes/api/public/setup-admin'
import { Route as AuthenticatedVaultCollectionsNewRouteImport } from './routes/_authenticated/vault/collections/new'
import { Route as ApiPublicV1CollectionsRouteImport } from './routes/api/public/v1/collections'
import { Route as ApiPublicV1ProvidersRouteImport } from './routes/api/public/v1/providers'
import { Route as ApiPublicV1UsageRouteImport } from './routes/api/public/v1/usage'
import { Route as ApiPublicV1KeysIndexRouteImport } from './routes/api/public/v1/keys/index'
import { Route as ApiPublicV1KeysNextRouteImport } from './routes/api/public/v1/keys/next'
import { Route as ApiPublicV1KeysRandomRouteImport } from './routes/api/public/v1/keys/random'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiAccessIndexRoute =
  AuthenticatedApiAccessIndexRouteImport.update({
    id: '/api-access/',
    path: '/api-access/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApiAccessNewRoute =
  AuthenticatedApiAccessNewRouteImport.update({
    id: '/api-access/new',
    path: '/api-access/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProvidersIndexRoute =
  AuthenticatedProvidersIndexRouteImport.update({
    id: '/providers/',
    path: '/providers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProvidersSlugRoute =
  AuthenticatedProvidersSlugRouteImport.update({
    id: '/providers/$slug',
    path: '/providers/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProvidersNewRoute =
  AuthenticatedProvidersNewRouteImport.update({
    id: '/providers/new',
    path: '/providers/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVaultIndexRoute = AuthenticatedVaultIndexRouteImport.update({
  id: '/vault/',
  path: '/vault/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVaultIdRoute = AuthenticatedVaultIdRouteImport.update({
  id: '/vault/$id',
  path: '/vault/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVaultExportRoute =
  AuthenticatedVaultExportRouteImport.update({
    id: '/vault/export',
    path: '/vault/export',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVaultImportRoute =
  AuthenticatedVaultImportRouteImport.update({
    id: '/vault/import',
    path: '/vault/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVaultNewRoute = AuthenticatedVaultNewRouteImport.update({
  id: '/vault/new',
  path: '/vault/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSetupAdminRoute = ApiPublicSetupAdminRouteImport.update({
  id: '/api/public/setup-admin',
  path: '/api/public/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVaultCollectionsNewRoute =
  AuthenticatedVaultCollectionsNewRouteImport.update({
    id: '/vault/collections/new',
    path: '/vault/collections/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicV1CollectionsRoute = ApiPublicV1CollectionsRouteImport.update({
  id: '/api/public/v1/collections',
  path: '/api/public/v1/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ProvidersRoute = ApiPublicV1ProvidersRouteImport.update({
  id: '/api/public/v1/providers',
  path: '/api/public/v1/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1UsageRoute = ApiPublicV1UsageRouteImport.update({
  id: '/api/public/v1/usage',
  path: '/api/public/v1/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1KeysIndexRoute = ApiPublicV1KeysIndexRouteImport.update({
  id: '/api/public/v1/keys/',
  path: '/api/public/v1/keys/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1KeysNextRoute = ApiPublicV1KeysNextRouteImport.update({
  id: '/api/public/v1/keys/next',
  path: '/api/public/v1/keys/next',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1KeysRandomRoute = ApiPublicV1KeysRandomRouteImport.update({
  id: '/api/public/v1/keys/random',
  path: '/api/public/v1/keys/random',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api-access/new': typeof AuthenticatedApiAccessNewRoute
  '/providers/$slug': typeof AuthenticatedProvidersSlugRoute
  '/providers/new': typeof AuthenticatedProvidersNewRoute
  '/vault/$id': typeof AuthenticatedVaultIdRoute
  '/vault/export': typeof AuthenticatedVaultExportRoute
  '/vault/import': typeof AuthenticatedVaultImportRoute
  '/vault/new': typeof AuthenticatedVaultNewRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/api-access/': typeof AuthenticatedApiAccessIndexRoute
  '/providers/': typeof AuthenticatedProvidersIndexRoute
  '/vault/': typeof AuthenticatedVaultIndexRoute
  '/vault/collections/new': typeof AuthenticatedVaultCollectionsNewRoute
  '/api/public/v1/collections': typeof ApiPublicV1CollectionsRoute
  '/api/public/v1/providers': typeof ApiPublicV1ProvidersRoute
  '/api/public/v1/usage': typeof ApiPublicV1UsageRoute
  '/api/public/v1/keys/next': typeof ApiPublicV1KeysNextRoute
  '/api/public/v1/keys/random': typeof ApiPublicV1KeysRandomRoute
  '/api/public/v1/keys/': typeof ApiPublicV1KeysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api-access/new': typeof AuthenticatedApiAccessNewRoute
  '/providers/$slug': typeof AuthenticatedProvidersSlugRoute
  '/providers/new': typeof AuthenticatedProvidersNewRoute
  '/vault/$id': typeof AuthenticatedVaultIdRoute
  '/vault/export': typeof AuthenticatedVaultExportRoute
  '/vault/import': typeof AuthenticatedVaultImportRoute
  '/vault/new': typeof AuthenticatedVaultNewRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/api-access': typeof AuthenticatedApiAccessIndexRoute
  '/providers': typeof AuthenticatedProvidersIndexRoute
  '/vault': typeof AuthenticatedVaultIndexRoute
  '/vault/collections/new': typeof AuthenticatedVaultCollectionsNewRoute
  '/api/public/v1/collections': typeof ApiPublicV1CollectionsRoute
  '/api/public/v1/providers': typeof ApiPublicV1ProvidersRoute
  '/api/public/v1/usage': typeof ApiPublicV1UsageRoute
  '/api/public/v1/keys/next': typeof ApiPublicV1KeysNextRoute
  '/api/public/v1/keys/random': typeof ApiPublicV1KeysRandomRoute
  '/api/public/v1/keys': typeof ApiPublicV1KeysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/api-access/new': typeof AuthenticatedApiAccessNewRoute
  '/_authenticated/providers/$slug': typeof AuthenticatedProvidersSlugRoute
  '/_authenticated/providers/new': typeof AuthenticatedProvidersNewRoute
  '/_authenticated/vault/$id': typeof AuthenticatedVaultIdRoute
  '/_authenticated/vault/export': typeof AuthenticatedVaultExportRoute
  '/_authenticated/vault/import': typeof AuthenticatedVaultImportRoute
  '/_authenticated/vault/new': typeof AuthenticatedVaultNewRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/_authenticated/api-access/': typeof AuthenticatedApiAccessIndexRoute
  '/_authenticated/providers/': typeof AuthenticatedProvidersIndexRoute
  '/_authenticated/vault/': typeof AuthenticatedVaultIndexRoute
  '/_authenticated/vault/collections/new': typeof AuthenticatedVaultCollectionsNewRoute
  '/api/public/v1/collections': typeof ApiPublicV1CollectionsRoute
  '/api/public/v1/providers': typeof ApiPublicV1ProvidersRoute
  '/api/public/v1/usage': typeof ApiPublicV1UsageRoute
  '/api/public/v1/keys/next': typeof ApiPublicV1KeysNextRoute
  '/api/public/v1/keys/random': typeof ApiPublicV1KeysRandomRoute
  '/api/public/v1/keys/': typeof ApiPublicV1KeysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/activity'
    | '/dashboard'
    | '/settings'
    | '/api-access/new'
    | '/providers/$slug'
    | '/providers/new'
    | '/vault/$id'
    | '/vault/export'
    | '/vault/import'
    | '/vault/new'
    | '/api/public/setup-admin'
    | '/api-access/'
    | '/providers/'
    | '/vault/'
    | '/vault/collections/new'
    | '/api/public/v1/collections'
    | '/api/public/v1/providers'
    | '/api/public/v1/usage'
    | '/api/public/v1/keys/next'
    | '/api/public/v1/keys/random'
    | '/api/public/v1/keys/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/activity'
    | '/dashboard'
    | '/settings'
    | '/api-access/new'
    | '/providers/$slug'
    | '/providers/new'
    | '/vault/$id'
    | '/vault/export'
    | '/vault/import'
    | '/vault/new'
    | '/api/public/setup-admin'
    | '/api-access'
    | '/providers'
    | '/vault'
    | '/vault/collections/new'
    | '/api/public/v1/collections'
    | '/api/public/v1/providers'
    | '/api/public/v1/usage'
    | '/api/public/v1/keys/next'
    | '/api/public/v1/keys/random'
    | '/api/public/v1/keys'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/activity'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/api-access/new'
    | '/_authenticated/providers/$slug'
    | '/_authenticated/providers/new'
    | '/_authenticated/vault/$id'
    | '/_authenticated/vault/export'
    | '/_authenticated/vault/import'
    | '/_authenticated/vault/new'
    | '/api/public/setup-admin'
    | '/_authenticated/api-access/'
    | '/_authenticated/providers/'
    | '/_authenticated/vault/'
    | '/_authenticated/vault/collections/new'
    | '/api/public/v1/collections'
    | '/api/public/v1/providers'
    | '/api/public/v1/usage'
    | '/api/public/v1/keys/next'
    | '/api/public/v1/keys/random'
    | '/api/public/v1/keys/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicSetupAdminRoute: typeof ApiPublicSetupAdminRoute
  ApiPublicV1CollectionsRoute: typeof ApiPublicV1CollectionsRoute
  ApiPublicV1ProvidersRoute: typeof ApiPublicV1ProvidersRoute
  ApiPublicV1UsageRoute: typeof ApiPublicV1UsageRoute
  ApiPublicV1KeysNextRoute: typeof ApiPublicV1KeysNextRoute
  ApiPublicV1KeysRandomRoute: typeof ApiPublicV1KeysRandomRoute
  ApiPublicV1KeysIndexRoute: typeof ApiPublicV1KeysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-access/': {
      id: '/_authenticated/api-access/'
      path: '/api-access'
      fullPath: '/api-access/'
      preLoaderRoute: typeof AuthenticatedApiAccessIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-access/new': {
      id: '/_authenticated/api-access/new'
      path: '/api-access/new'
      fullPath: '/api-access/new'
      preLoaderRoute: typeof AuthenticatedApiAccessNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/providers/': {
      id: '/_authenticated/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof AuthenticatedProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/providers/$slug': {
      id: '/_authenticated/providers/$slug'
      path: '/providers/$slug'
      fullPath: '/providers/$slug'
      preLoaderRoute: typeof AuthenticatedProvidersSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/providers/new': {
      id: '/_authenticated/providers/new'
      path: '/providers/new'
      fullPath: '/providers/new'
      preLoaderRoute: typeof AuthenticatedProvidersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vault/': {
      id: '/_authenticated/vault/'
      path: '/vault'
      fullPath: '/vault/'
      preLoaderRoute: typeof AuthenticatedVaultIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vault/$id': {
      id: '/_authenticated/vault/$id'
      path: '/vault/$id'
      fullPath: '/vault/$id'
      preLoaderRoute: typeof AuthenticatedVaultIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vault/export': {
      id: '/_authenticated/vault/export'
      path: '/vault/export'
      fullPath: '/vault/export'
      preLoaderRoute: typeof AuthenticatedVaultExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vault/import': {
      id: '/_authenticated/vault/import'
      path: '/vault/import'
      fullPath: '/vault/import'
      preLoaderRoute: typeof AuthenticatedVaultImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vault/new': {
      id: '/_authenticated/vault/new'
      path: '/vault/new'
      fullPath: '/vault/new'
      preLoaderRoute: typeof AuthenticatedVaultNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/setup-admin': {
      id: '/api/public/setup-admin'
      path: '/api/public/setup-admin'
      fullPath: '/api/public/setup-admin'
      preLoaderRoute: typeof ApiPublicSetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vault/collections/new': {
      id: '/_authenticated/vault/collections/new'
      path: '/vault/collections/new'
      fullPath: '/vault/collections/new'
      preLoaderRoute: typeof AuthenticatedVaultCollectionsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/v1/collections': {
      id: '/api/public/v1/collections'
      path: '/api/public/v1/collections'
      fullPath: '/api/public/v1/collections'
      preLoaderRoute: typeof ApiPublicV1CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/providers': {
      id: '/api/public/v1/providers'
      path: '/api/public/v1/providers'
      fullPath: '/api/public/v1/providers'
      preLoaderRoute: typeof ApiPublicV1ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/usage': {
      id: '/api/public/v1/usage'
      path: '/api/public/v1/usage'
      fullPath: '/api/public/v1/usage'
      preLoaderRoute: typeof ApiPublicV1UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/keys/': {
      id: '/api/public/v1/keys/'
      path: '/api/public/v1/keys'
      fullPath: '/api/public/v1/keys/'
      preLoaderRoute: typeof ApiPublicV1KeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/keys/next': {
      id: '/api/public/v1/keys/next'
      path: '/api/public/v1/keys/next'
      fullPath: '/api/public/v1/keys/next'
      preLoaderRoute: typeof ApiPublicV1KeysNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/keys/random': {
      id: '/api/public/v1/keys/random'
      path: '/api/public/v1/keys/random'
      fullPath: '/api/public/v1/keys/random'
      preLoaderRoute: typeof ApiPublicV1KeysRandomRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedApiAccessNewRoute: typeof AuthenticatedApiAccessNewRoute
  AuthenticatedProvidersSlugRoute: typeof AuthenticatedProvidersSlugRoute
  AuthenticatedProvidersNewRoute: typeof AuthenticatedProvidersNewRoute
  AuthenticatedVaultIdRoute: typeof AuthenticatedVaultIdRoute
  AuthenticatedVaultExportRoute: typeof AuthenticatedVaultExportRoute
  AuthenticatedVaultImportRoute: typeof AuthenticatedVaultImportRoute
  AuthenticatedVaultNewRoute: typeof AuthenticatedVaultNewRoute
  AuthenticatedApiAccessIndexRoute: typeof AuthenticatedApiAccessIndexRoute
  AuthenticatedProvidersIndexRoute: typeof AuthenticatedProvidersIndexRoute
  AuthenticatedVaultIndexRoute: typeof AuthenticatedVaultIndexRoute
  AuthenticatedVaultCollectionsNewRoute: typeof AuthenticatedVaultCollectionsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedApiAccessNewRoute: AuthenticatedApiAccessNewRoute,
  AuthenticatedProvidersSlugRoute: AuthenticatedProvidersSlugRoute,
  AuthenticatedProvidersNewRoute: AuthenticatedProvidersNewRoute,
  AuthenticatedVaultIdRoute: AuthenticatedVaultIdRoute,
  AuthenticatedVaultExportRoute: AuthenticatedVaultExportRoute,
  AuthenticatedVaultImportRoute: AuthenticatedVaultImportRoute,
  AuthenticatedVaultNewRoute: AuthenticatedVaultNewRoute,
  AuthenticatedApiAccessIndexRoute: AuthenticatedApiAccessIndexRoute,
  AuthenticatedProvidersIndexRoute: AuthenticatedProvidersIndexRoute,
  AuthenticatedVaultIndexRoute: AuthenticatedVaultIndexRoute,
  AuthenticatedVaultCollectionsNewRoute: AuthenticatedVaultCollectionsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicSetupAdminRoute: ApiPublicSetupAdminRoute,
  ApiPublicV1CollectionsRoute: ApiPublicV1CollectionsRoute,
  ApiPublicV1ProvidersRoute: ApiPublicV1ProvidersRoute,
  ApiPublicV1UsageRoute: ApiPublicV1UsageRoute,
  ApiPublicV1KeysNextRoute: ApiPublicV1KeysNextRoute,
  ApiPublicV1KeysRandomRoute: ApiPublicV1KeysRandomRoute,
  ApiPublicV1KeysIndexRoute: ApiPublicV1KeysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
