/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicSetupAdminRouteImport } from './routes/api/public/setup-admin'
import { Route as ApiPublicV1CollectionsRouteImport } from './routes/api/public/v1/collections'
import { Route as ApiPublicV1ProvidersRouteImport } from './routes/api/public/v1/providers'
import { Route as ApiPublicV1UsageRouteImport } from './routes/api/public/v1/usage'
import { Route as ApiPublicV1KeysIndexRouteImport } from './routes/api/public/v1/keys/index'
import { Route as ApiPublicV1KeysNextRouteImport } from './routes/api/public/v1/keys/next'
import { Route as ApiPublicV1KeysRandomRouteImport } from './routes/api/public/v1/keys/random'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSetupAdminRoute = ApiPublicSetupAdminRouteImport.update({
  id: '/api/public/setup-admin',
  path: '/api/public/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CollectionsRoute = ApiPublicV1CollectionsRouteImport.update({
  id: '/api/public/v1/collections',
  path: '/api/public/v1/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ProvidersRoute = ApiPublicV1ProvidersRouteImport.update({
  id: '/api/public/v1/providers',
  path: '/api/public/v1/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1UsageRoute = ApiPublicV1UsageRouteImport.update({
  id: '/api/public/v1/usage',
  path: '/api/public/v1/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1KeysIndexRoute = ApiPublicV1KeysIndexRouteImport.update({
  id: '/api/public/v1/keys/',
  path: '/api/public/v1/keys/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1KeysNextRoute = ApiPublicV1KeysNextRouteImport.update({
  id: '/api/public/v1/keys/next',
  path: '/api/public/v1/keys/next',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1KeysRandomRoute = ApiPublicV1KeysRandomRouteImport.update({
  id: '/api/public/v1/keys/random',
  path: '/api/public/v1/keys/random',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/api/public/v1/collections': typeof ApiPublicV1CollectionsRoute
  '/api/public/v1/providers': typeof ApiPublicV1ProvidersRoute
  '/api/public/v1/usage': typeof ApiPublicV1UsageRoute
  '/api/public/v1/keys/next': typeof ApiPublicV1KeysNextRoute
  '/api/public/v1/keys/random': typeof ApiPublicV1KeysRandomRoute
  '/api/public/v1/keys/': typeof ApiPublicV1KeysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/api/public/v1/collections': typeof ApiPublicV1CollectionsRoute
  '/api/public/v1/providers': typeof ApiPublicV1ProvidersRoute
  '/api/public/v1/usage': typeof ApiPublicV1UsageRoute
  '/api/public/v1/keys/next': typeof ApiPublicV1KeysNextRoute
  '/api/public/v1/keys/random': typeof ApiPublicV1KeysRandomRoute
  '/api/public/v1/keys': typeof ApiPublicV1KeysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/api/public/v1/collections': typeof ApiPublicV1CollectionsRoute
  '/api/public/v1/providers': typeof ApiPublicV1ProvidersRoute
  '/api/public/v1/usage': typeof ApiPublicV1UsageRoute
  '/api/public/v1/keys/next': typeof ApiPublicV1KeysNextRoute
  '/api/public/v1/keys/random': typeof ApiPublicV1KeysRandomRoute
  '/api/public/v1/keys/': typeof ApiPublicV1KeysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/api/public/setup-admin'
    | '/api/public/v1/collections'
    | '/api/public/v1/providers'
    | '/api/public/v1/usage'
    | '/api/public/v1/keys/next'
    | '/api/public/v1/keys/random'
    | '/api/public/v1/keys/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/api/public/setup-admin'
    | '/api/public/v1/collections'
    | '/api/public/v1/providers'
    | '/api/public/v1/usage'
    | '/api/public/v1/keys/next'
    | '/api/public/v1/keys/random'
    | '/api/public/v1/keys'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/api/public/setup-admin'
    | '/api/public/v1/collections'
    | '/api/public/v1/providers'
    | '/api/public/v1/usage'
    | '/api/public/v1/keys/next'
    | '/api/public/v1/keys/random'
    | '/api/public/v1/keys/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicSetupAdminRoute: typeof ApiPublicSetupAdminRoute
  ApiPublicV1CollectionsRoute: typeof ApiPublicV1CollectionsRoute
  ApiPublicV1ProvidersRoute: typeof ApiPublicV1ProvidersRoute
  ApiPublicV1UsageRoute: typeof ApiPublicV1UsageRoute
  ApiPublicV1KeysNextRoute: typeof ApiPublicV1KeysNextRoute
  ApiPublicV1KeysRandomRoute: typeof ApiPublicV1KeysRandomRoute
  ApiPublicV1KeysIndexRoute: typeof ApiPublicV1KeysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/setup-admin': {
      id: '/api/public/setup-admin'
      path: '/api/public/setup-admin'
      fullPath: '/api/public/setup-admin'
      preLoaderRoute: typeof ApiPublicSetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/collections': {
      id: '/api/public/v1/collections'
      path: '/api/public/v1/collections'
      fullPath: '/api/public/v1/collections'
      preLoaderRoute: typeof ApiPublicV1CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/providers': {
      id: '/api/public/v1/providers'
      path: '/api/public/v1/providers'
      fullPath: '/api/public/v1/providers'
      preLoaderRoute: typeof ApiPublicV1ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/usage': {
      id: '/api/public/v1/usage'
      path: '/api/public/v1/usage'
      fullPath: '/api/public/v1/usage'
      preLoaderRoute: typeof ApiPublicV1UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/keys/': {
      id: '/api/public/v1/keys/'
      path: '/api/public/v1/keys'
      fullPath: '/api/public/v1/keys/'
      preLoaderRoute: typeof ApiPublicV1KeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/keys/next': {
      id: '/api/public/v1/keys/next'
      path: '/api/public/v1/keys/next'
      fullPath: '/api/public/v1/keys/next'
      preLoaderRoute: typeof ApiPublicV1KeysNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/keys/random': {
      id: '/api/public/v1/keys/random'
      path: '/api/public/v1/keys/random'
      fullPath: '/api/public/v1/keys/random'
      preLoaderRoute: typeof ApiPublicV1KeysRandomRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicSetupAdminRoute: ApiPublicSetupAdminRoute,
  ApiPublicV1CollectionsRoute: ApiPublicV1CollectionsRoute,
  ApiPublicV1ProvidersRoute: ApiPublicV1ProvidersRoute,
  ApiPublicV1UsageRoute: ApiPublicV1UsageRoute,
  ApiPublicV1KeysNextRoute: ApiPublicV1KeysNextRoute,
  ApiPublicV1KeysRandomRoute: ApiPublicV1KeysRandomRoute,
  ApiPublicV1KeysIndexRoute: ApiPublicV1KeysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
